// <auto-generated />
namespace SMARTplanner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ItemCreator_ProjectDescr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemCreator_ProjectDescr));
        
        string IMigrationMetadata.Id
        {
            get { return "201603121235098_ItemCreator_ProjectDescr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
